remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Welcome Dark world
description: I am doing my homework
show_downloads: "true" or "false" (unquoted) to indicate whether to provide a download URL]
theme: jekll-theme-midnight
